name: Build Artifacts

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 3
  CMAKE_TOOLCHAIN_FILE: ${{ github.workspace }}/libdave/cpp/vcpkg/scripts/buildsystems/vcpkg.cmake
  VCPKG_BINARY_SOURCES: files,${{ github.workspace }}/libdave/vcpkg_cache,readwrite
  VCPKG_DISABLE_METRICS: 1

jobs:
  build:
    name: Build Linux x64
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/build_linux

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Linux_x64
          path: |
            api/build/libs/*.jar
            native/build/libs/*.jar