name: Build Artifacts

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux
            runner: ubuntu-latest
          - target: aarch64-unknown-linux
            runner: ubuntu-latest
            skip-test: true
          - target: x86_64-pc-windows-msvc
            runner: windows-latest
          - target: darwin
            runner: macos-latest

    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v6

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Artifacts
        run: ./gradlew build -Ptarget=${{ matrix.target }} -x test

      - name: Run Tests
        if: ${{ !matrix.skip-test }}
        run: ./gradlew test

      - name: Upload Test Reports
        if: failure()
        uses: actions/upload-artifact@v6
        with:
          name: test-reports-${{ matrix.target }}
          path: |
            **/build/reports/tests/**/*.html
            **/build/test-results/**/*.xml

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: |
            api/build/libs/*.jar
            native/build/libs/*.jar
