name: Build Artifacts

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 3
  CMAKE_TOOLCHAIN_FILE: ${{ github.workspace }}/libdave/cpp/vcpkg/scripts/buildsystems/vcpkg.cmake
  VCPKG_BINARY_SOURCES: files,${{ github.workspace }}/libdave/vcpkg_cache,readwrite
  VCPKG_DISABLE_METRICS: 1

jobs:
  linux:
    name: Build Linux x64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build Artifacts
        uses: ./.github/actions/build_linux

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Linux_x64
          path: |
            api/build/libs/*.jar
            native/build/libs/*.jar

      - name: Upload JUnit XML Test Report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v6
        with:
          name: junit-xml-test-report
          path: native/build/test-results/test

      - name: Upload HTML Test Report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v6
        with:
          name: junit-html-test-report
          path: native/build/reports/tests/test

      - name: Annotate Failed Tests
        uses: mikepenz/action-junit-report@v6
        if: ${{ !cancelled() }}
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          annotate_only: 'true'
          test_files_prefix: 'native/'

  windows:
    name: Build Windows x64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Bootstrap vcpkg
        run: native/libdave/cpp/vcpkg/bootstrap-vcpkg.bat

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Artifacts
        run: ./gradlew build -Ptarget=x86_64-pc-windows-msvc

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows_x64
          path: |
            api/build/libs/*.jar
            native/build/libs/*.jar